# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17DdJlMq-1DHmOA7JX4T3wOLvbATv_T3o
"""

import streamlit as st
import pandas as pd
import numpy as np

# Title of the dashboard
st.title("Simple Dashboard Example")

# Sidebar for user input
st.sidebar.header("User Input")

# User input for data size
data_size = st.sidebar.slider("Select data size", 100, 1000, 500)

# Generate random data
data = pd.DataFrame(
    np.random.randn(data_size, 3),
    columns=["Column A", "Column B", "Column C"]
)

# Display data
st.subheader("Random Data")
st.write(data)

# Display a line chart
st.subheader("Line Chart")
st.line_chart(data)

# Display a bar chart
st.subheader("Bar Chart")
st.bar_chart(data)

# Display a map (if the data is in a suitable format)
if st.checkbox("Show data on map"):
    map_data = pd.DataFrame(
        np.random.randn(1000, 2) / [50, 50] + [37.76, -122.4],
        columns=["lat", "lon"]
    )
    st.map(map_data)

# Footer
st.write("This is a simple dashboard")